/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.panastech.backendsgds.view.home;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import javax.swing.JFrame;

import com.panastech.backendsgds.view.ControleView;
import com.panastech.backendsgds.view.home.popups.popUpFileChooser;
import com.panastech.backendsgds.view.home.popups.popUpSolicitarExame;

/**
 *
 * @author Dev
 */
public class Home extends javax.swing.JFrame {
    private final ControleView controleView;

    private boolean telaCheia = false;
    private boolean chooseFile = false;

    public Home(ControleView controleView) {
        this.controleView = controleView;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abasMenu = new javax.swing.JTabbedPane();
        painelAgendamento = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        informacao = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        conteinerEspecialidade = new javax.swing.JPanel();
        conteinerTitulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        conteinerLista = new javax.swing.JPanel();
        listaSuspEspecialidade = new javax.swing.JComboBox<>();
        conteinerLocal = new javax.swing.JPanel();
        conteinerTitulo1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        conteinerLista1 = new javax.swing.JPanel();
        listaSuspLocal = new javax.swing.JComboBox<>();
        conteinerCargo = new javax.swing.JPanel();
        conteinerTitulo2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        conteinerTxtField2 = new javax.swing.JPanel();
        listaSuspData = new javax.swing.JComboBox<>();
        conteinerConfirmar = new javax.swing.JPanel();
        conteinerEntrar1 = new javax.swing.JPanel();
        conteinerTitulo4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        conteinerTxtField3 = new javax.swing.JPanel();
        txtCPF = new javax.swing.JTextField();
        conteinerBtnConfirmar = new javax.swing.JPanel();
        btnConfirmar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgendamentos = new javax.swing.JTable();
        painelExames = new javax.swing.JPanel();
        cabecalho = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        exames = new javax.swing.JTabbedPane();
        conteinerExamesRealizados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaExamesRealizados = new javax.swing.JTable();
        conteinerExamesSolicitados = new javax.swing.JPanel();
        rodapeExamesSolicitados = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCarregarExameRealizado = new javax.swing.JButton();
        btnSolicitarNovoExame = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaExamesSolicitados = new javax.swing.JTable();
        painelHistoricoMed = new javax.swing.JPanel();
        painelProfissional = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGDS © PanasTech");
        setBackground(new java.awt.Color(87, 122, 137));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(900, 500));

        abasMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        abasMenu.setToolTipText("");
        abasMenu.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        abasMenu.setPreferredSize(new java.awt.Dimension(700, 500));

        painelAgendamento.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(87, 122, 137));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 75));

        jPanel12.setBackground(new java.awt.Color(87, 122, 137));
        jPanel12.setPreferredSize(new java.awt.Dimension(400, 75));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 350, Short.MAX_VALUE));
        jPanel12Layout.setVerticalGroup(
                jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE));

        jPanel14.setBackground(new java.awt.Color(87, 122, 137));
        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 10));

        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Agendamentos");
        jPanel14.add(jLabel8);

        jPanel15.setBackground(new java.awt.Color(87, 122, 137));
        jPanel15.setPreferredSize(new java.awt.Dimension(400, 75));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 254, Short.MAX_VALUE));
        jPanel15Layout.setVerticalGroup(
                jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 350,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 367,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 254,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        painelAgendamento.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(4, 56, 79));
        jPanel8.setPreferredSize(new java.awt.Dimension(700, 3000));
        jPanel8.setLayout(new java.awt.BorderLayout());

        informacao.setBackground(new java.awt.Color(95, 133, 138));
        informacao.setPreferredSize(new java.awt.Dimension(350, 3000));
        informacao.setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setAutoscrolls(true);
        jPanel11.setPreferredSize(new java.awt.Dimension(350, 425));
        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 1));

        conteinerEspecialidade.setBackground(new java.awt.Color(87, 122, 137));
        conteinerEspecialidade.setAutoscrolls(true);
        conteinerEspecialidade.setPreferredSize(new java.awt.Dimension(350, 80));
        conteinerEspecialidade.setRequestFocusEnabled(false);
        conteinerEspecialidade.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerTitulo.setBackground(new java.awt.Color(255, 255, 255));
        conteinerTitulo.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerTitulo.setLayout(new java.awt.BorderLayout());

        jLabel4.setBackground(new java.awt.Color(87, 122, 137));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 40, 45));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Especialidade");
        conteinerTitulo.add(jLabel4, java.awt.BorderLayout.CENTER);

        conteinerEspecialidade.add(conteinerTitulo);

        conteinerLista.setBackground(new java.awt.Color(255, 255, 255));
        conteinerLista.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerLista.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        conteinerLista.add(listaSuspEspecialidade);

        conteinerEspecialidade.add(conteinerLista);

        jPanel11.add(conteinerEspecialidade);

        conteinerLocal.setBackground(new java.awt.Color(87, 122, 137));
        conteinerLocal.setAutoscrolls(true);
        conteinerLocal.setOpaque(false);
        conteinerLocal.setPreferredSize(new java.awt.Dimension(350, 80));
        conteinerLocal.setRequestFocusEnabled(false);
        conteinerLocal.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerTitulo1.setBackground(new java.awt.Color(87, 122, 137));
        conteinerTitulo1.setOpaque(false);
        conteinerTitulo1.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerTitulo1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 40, 45));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Local");
        conteinerTitulo1.add(jLabel5, java.awt.BorderLayout.CENTER);

        conteinerLocal.add(conteinerTitulo1);

        conteinerLista1.setOpaque(false);
        conteinerLista1.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerLista1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerLista1.add(listaSuspLocal);

        conteinerLocal.add(conteinerLista1);

        jPanel11.add(conteinerLocal);

        conteinerCargo.setBackground(new java.awt.Color(87, 122, 137));
        conteinerCargo.setAutoscrolls(true);
        conteinerCargo.setOpaque(false);
        conteinerCargo.setPreferredSize(new java.awt.Dimension(350, 80));
        conteinerCargo.setRequestFocusEnabled(false);
        conteinerCargo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerTitulo2.setBackground(new java.awt.Color(87, 122, 137));
        conteinerTitulo2.setOpaque(false);
        conteinerTitulo2.setPreferredSize(new java.awt.Dimension(350, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(29, 40, 45));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escolha uma data");

        javax.swing.GroupLayout conteinerTitulo2Layout = new javax.swing.GroupLayout(conteinerTitulo2);
        conteinerTitulo2.setLayout(conteinerTitulo2Layout);
        conteinerTitulo2Layout.setHorizontalGroup(
                conteinerTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                conteinerTitulo2Layout.createSequentialGroup()
                                        .addContainerGap(102, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addContainerGap(94, Short.MAX_VALUE)));
        conteinerTitulo2Layout.setVerticalGroup(
                conteinerTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(conteinerTitulo2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 14, Short.MAX_VALUE)));

        conteinerCargo.add(conteinerTitulo2);

        conteinerTxtField2.setOpaque(false);
        conteinerTxtField2.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerTxtField2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        conteinerTxtField2.add(listaSuspData);

        conteinerCargo.add(conteinerTxtField2);

        jPanel11.add(conteinerCargo);

        conteinerConfirmar.setBackground(new java.awt.Color(87, 122, 137));
        conteinerConfirmar.setAutoscrolls(true);
        conteinerConfirmar.setOpaque(false);
        conteinerConfirmar.setRequestFocusEnabled(false);
        conteinerConfirmar.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerEntrar1.setBackground(new java.awt.Color(87, 122, 137));
        conteinerEntrar1.setAutoscrolls(true);
        conteinerEntrar1.setOpaque(false);
        conteinerEntrar1.setPreferredSize(new java.awt.Dimension(350, 80));
        conteinerEntrar1.setRequestFocusEnabled(false);
        conteinerEntrar1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        conteinerTitulo4.setBackground(new java.awt.Color(87, 122, 137));
        conteinerTitulo4.setOpaque(false);
        conteinerTitulo4.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerTitulo4.setLayout(new java.awt.GridBagLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(29, 40, 45));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Confirme seu CPF");
        conteinerTitulo4.add(jLabel7, new java.awt.GridBagConstraints());

        conteinerEntrar1.add(conteinerTitulo4);

        conteinerTxtField3.setOpaque(false);
        conteinerTxtField3.setPreferredSize(new java.awt.Dimension(350, 40));
        conteinerTxtField3.setLayout(new java.awt.GridBagLayout());

        txtCPF.setPreferredSize(new java.awt.Dimension(300, 30));
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        conteinerTxtField3.add(txtCPF, new java.awt.GridBagConstraints());

        conteinerEntrar1.add(conteinerTxtField3);

        conteinerConfirmar.add(conteinerEntrar1);

        jPanel11.add(conteinerConfirmar);

        conteinerBtnConfirmar.setOpaque(false);
        conteinerBtnConfirmar.setPreferredSize(new java.awt.Dimension(350, 40));

        btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmar.setSelected(true);
        btnConfirmar.setText("Verificar");
        btnConfirmar.setIconTextGap(5);
        btnConfirmar.setPreferredSize(new java.awt.Dimension(150, 40));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conteinerBtnConfirmarLayout = new javax.swing.GroupLayout(conteinerBtnConfirmar);
        conteinerBtnConfirmar.setLayout(conteinerBtnConfirmarLayout);
        conteinerBtnConfirmarLayout.setHorizontalGroup(
                conteinerBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(conteinerBtnConfirmarLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 302,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE)));
        conteinerBtnConfirmarLayout.setVerticalGroup(
                conteinerBtnConfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        jPanel11.add(conteinerBtnConfirmar);

        informacao.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel8.add(informacao, java.awt.BorderLayout.WEST);

        jScrollPane1.setBackground(new java.awt.Color(87, 122, 137));
        jScrollPane1.setOpaque(false);

        tabelaAgendamentos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaAgendamentos.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { "TESTE ESPECIALIDADE", "TESTE LOCAL", "TESTE DATA", "TESTE HORA", "TESTE MEDICO" }
                },
                new String[] {
                        "Especialidade", "Local", "Data", "Hora", "Médico"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tabelaAgendamentos.setCellSelectionEnabled(true);
        tabelaAgendamentos.setDefaultEditor(Object.class, null);
        tabelaAgendamentos.setShowGrid(true);
        jScrollPane1.setViewportView(tabelaAgendamentos);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        painelAgendamento.add(jPanel8, java.awt.BorderLayout.CENTER);

        abasMenu.addTab("Agendamento", painelAgendamento);

        painelExames.setBackground(new java.awt.Color(95, 133, 138));
        painelExames.setLayout(new java.awt.BorderLayout());

        cabecalho.setBackground(new java.awt.Color(87, 122, 137));
        cabecalho.setPreferredSize(new java.awt.Dimension(1467, 75));

        jPanel7.setBackground(new java.awt.Color(87, 122, 137));
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 75));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 140, Short.MAX_VALUE));
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE));

        jPanel6.setBackground(new java.awt.Color(87, 122, 137));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 10));

        jLabel3.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Exames");
        jPanel6.add(jLabel3);

        jPanel5.setBackground(new java.awt.Color(87, 122, 137));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 75));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 115, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE));

        javax.swing.GroupLayout cabecalhoLayout = new javax.swing.GroupLayout(cabecalho);
        cabecalho.setLayout(cabecalhoLayout);
        cabecalhoLayout.setHorizontalGroup(
                cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(cabecalhoLayout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 263,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 367,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 282,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        cabecalhoLayout.setVerticalGroup(
                cabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 75,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        painelExames.add(cabecalho, java.awt.BorderLayout.PAGE_START);

        exames.setBackground(new java.awt.Color(255, 255, 255));
        exames.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        exames.setAlignmentX(1.0F);
        exames.setAlignmentY(1.0F);
        exames.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exames.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        conteinerExamesRealizados.setLayout(new java.awt.BorderLayout());

        tabelaExamesRealizados.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaExamesRealizados.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tabelaExamesRealizados.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { "TESTE EXAME", "TESTE LOCAL", "TESTE DATA/HORA", "TESTE PROTOCOLO" }
                },
                new String[] {
                        "Exame", "Local", "Data/Hora", "Protocolo"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tabelaExamesRealizados.setCellSelectionEnabled(true);
        tabelaExamesRealizados.setDefaultEditor(Object.class, null);
        jScrollPane2.setViewportView(tabelaExamesRealizados);

        conteinerExamesRealizados.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        exames.addTab("Realizados", conteinerExamesRealizados);

        conteinerExamesSolicitados.setLayout(new java.awt.BorderLayout());

        rodapeExamesSolicitados.setBackground(new java.awt.Color(29, 40, 45));
        rodapeExamesSolicitados.setPreferredSize(new java.awt.Dimension(0, 75));

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 75));

        btnCarregarExameRealizado.setText("Carregar exame realizado");
        btnCarregarExameRealizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarExameRealizadoActionPerformed(evt);
            }
        });

        btnSolicitarNovoExame.setText("Solicitar novo exame");
        btnSolicitarNovoExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarNovoExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 432, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnSolicitarNovoExame, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCarregarExameRealizado, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(58, Short.MAX_VALUE))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnSolicitarNovoExame,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCarregarExameRealizado,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 75));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 268, Short.MAX_VALUE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 75, Short.MAX_VALUE));

        javax.swing.GroupLayout rodapeExamesSolicitadosLayout = new javax.swing.GroupLayout(rodapeExamesSolicitados);
        rodapeExamesSolicitados.setLayout(rodapeExamesSolicitadosLayout);
        rodapeExamesSolicitadosLayout.setHorizontalGroup(
                rodapeExamesSolicitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rodapeExamesSolicitadosLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 268,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 432,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        rodapeExamesSolicitadosLayout.setVerticalGroup(
                rodapeExamesSolicitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        conteinerExamesSolicitados.add(rodapeExamesSolicitados, java.awt.BorderLayout.PAGE_END);

        tabelaExamesSolicitados
                .setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaExamesSolicitados.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        tabelaExamesSolicitados.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { "TESTE EXAME", "TESTE LOCAL", "TESTE DATA/HORA", "TESTE PROTOCOLO", "TESTE SOLICITAÇÃO" }
                },
                new String[] {
                        "Exame", "Local", "Data/Hora", "Protocolo", "Nº da Solicitação"
                }) {
            Class[] types = new Class[] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,
                    java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        tabelaExamesSolicitados.setCellSelectionEnabled(true);
        tabelaExamesSolicitados.setDefaultEditor(Object.class, null);
        jScrollPane3.setViewportView(tabelaExamesSolicitados);

        conteinerExamesSolicitados.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        exames.addTab("Solicitados", conteinerExamesSolicitados);

        painelExames.add(exames, java.awt.BorderLayout.CENTER);
        exames.getAccessibleContext().setAccessibleDescription("");

        abasMenu.addTab("Exames", painelExames);

        javax.swing.GroupLayout painelHistoricoMedLayout = new javax.swing.GroupLayout(painelHistoricoMed);
        painelHistoricoMed.setLayout(painelHistoricoMedLayout);
        painelHistoricoMedLayout.setHorizontalGroup(
                painelHistoricoMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1167, Short.MAX_VALUE));
        painelHistoricoMedLayout.setVerticalGroup(
                painelHistoricoMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 462, Short.MAX_VALUE));

        abasMenu.addTab("Histórico Médico", painelHistoricoMed);

        javax.swing.GroupLayout painelProfissionalLayout = new javax.swing.GroupLayout(painelProfissional);
        painelProfissional.setLayout(painelProfissionalLayout);
        painelProfissionalLayout.setHorizontalGroup(
                painelProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1167, Short.MAX_VALUE));
        painelProfissionalLayout.setVerticalGroup(
                painelProfissionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 462, Short.MAX_VALUE));

        abasMenu.addTab("Profissional", painelProfissional);

        getContentPane().add(abasMenu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCPFActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnConfirmarActionPerformed

    private void btnSolicitarNovoExameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSolicitarNovoExameActionPerformed
        // TODO add your handling code here:
        popUpSolicitarExame solicitarExame = new popUpSolicitarExame(controleView);
        solicitarExame.setLocationRelativeTo(null);
        solicitarExame.setVisible(true);
    }// GEN-LAST:event_btnSolicitarNovoExameActionPerformed

    private void btnCarregarExameRealizadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCarregarExameRealizadoActionPerformed
        // TODO add your handling code here:

        popUpFileChooser poChooser = new popUpFileChooser();
        poChooser.setLocationRelativeTo(null);
        poChooser.setVisible(true);

    }// GEN-LAST:event_btnCarregarExameRealizadoActionPerformed

    private void alternarTelaCheia() {
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();

        if (!telaCheia) {
            setUndecorated(true);
            gd.setFullScreenWindow(this);
            telaCheia = true;
        } else {
            setUndecorated(false);
            gd.setFullScreenWindow(null);
            telaCheia = false;
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abasMenu;
    private javax.swing.JButton btnCarregarExameRealizado;
    private javax.swing.JToggleButton btnConfirmar;
    private javax.swing.JButton btnSolicitarNovoExame;
    private javax.swing.JPanel cabecalho;
    private javax.swing.JPanel conteinerBtnConfirmar;
    private javax.swing.JPanel conteinerCargo;
    private javax.swing.JPanel conteinerConfirmar;
    private javax.swing.JPanel conteinerEntrar1;
    private javax.swing.JPanel conteinerEspecialidade;
    private javax.swing.JPanel conteinerExamesRealizados;
    private javax.swing.JPanel conteinerExamesSolicitados;
    private javax.swing.JPanel conteinerLista;
    private javax.swing.JPanel conteinerLista1;
    private javax.swing.JPanel conteinerLocal;
    private javax.swing.JPanel conteinerTitulo;
    private javax.swing.JPanel conteinerTitulo1;
    private javax.swing.JPanel conteinerTitulo2;
    private javax.swing.JPanel conteinerTitulo4;
    private javax.swing.JPanel conteinerTxtField2;
    private javax.swing.JPanel conteinerTxtField3;
    private javax.swing.JTabbedPane exames;
    private javax.swing.JPanel informacao;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> listaSuspData;
    private javax.swing.JComboBox<String> listaSuspEspecialidade;
    private javax.swing.JComboBox<String> listaSuspLocal;
    private javax.swing.JPanel painelAgendamento;
    private javax.swing.JPanel painelExames;
    private javax.swing.JPanel painelHistoricoMed;
    private javax.swing.JPanel painelProfissional;
    private javax.swing.JPanel rodapeExamesSolicitados;
    private javax.swing.JTable tabelaAgendamentos;
    private javax.swing.JTable tabelaExamesRealizados;
    private javax.swing.JTable tabelaExamesSolicitados;
    private javax.swing.JTextField txtCPF;
    // End of variables declaration//GEN-END:variables

    public void setIsFrame2Open(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
                                                                       // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
